---
# handlers file for ansible-consul

- name: restart consul on Linux
  service:
    name: consul
    state: restarted
  when: ansible_os_family != "Windows"
  listen: 'restart consul'

- name: restart systemd-resolved
  service: name=systemd-resolved state=restarted enabled=yes
  listen: 'restart systemd-resolved'

- name: restart dnsmasq
  service: name=dnsmasq state=restarted enabled=yes
  listen: 'restart dnsmasq'

- name: reload consul
  command: /usr/local/bin/consul reload
